name: 💡 Ideas
description: Share your ideas for new features or improvements
title: "[IDEA] "
labels: ["idea", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing your idea! Please provide as much detail as possible to help us understand and evaluate your suggestion.

  - type: textarea
    id: idea-description
    attributes:
      label: 💡 Idea Description
      description: Describe your idea in detail
      placeholder: What would you like to see in GFMirror?
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: 🎯 Use Case
      description: How would this feature be used?
      placeholder: Describe the specific use case and who would benefit from this feature
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: ✨ Benefits
      description: What benefits would this provide?
      placeholder: Explain the advantages and value this would add to the app

  - type: textarea
    id: implementation
    attributes:
      label: 🔧 Implementation Ideas
      description: Do you have any ideas about how this could be implemented?
      placeholder: Share any technical thoughts or implementation approaches you have in mind

  - type: dropdown
    id: priority
    attributes:
      label: 📊 Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be useful
        - High - Really want this
        - Critical - Essential for my use case
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing discussions to avoid duplicates
          required: true
        - label: I have provided a clear description of the idea
          required: true
        - label: I have explained the use case and benefits
          required: true
